# Site Information
site_name: 'Roblox Logger Documentation'

# Repo information
repo_name: 'froghopperjacob/Roblox-Logger'
repo_url: 'https://github.com/froghopperjacob/Roblox-Logger'

# MKDocs information
theme:
  name: 'material'
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'
  feature:
    tabs: true

nav:
  - Home: index.md
  - Bug Tracker: https://github.com/froghopperjacob/Roblox-Logger/issues

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true